# Generated by Django 3.0.7 on 2020-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmine_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
